kind: Service
apiVersion: v1
metadata:
  namespace: staple
  name: staple-service
  labels:
    app: staple-service
    app.kubernetes.io/name: staple-service
    app.kubernetes.io/instance: staple-service
spec:
  selector:
    app: staple-service
    app.kubernetes.io/name: staple-service
    app.kubernetes.io/instance: staple-service
  ports:
  - name: staple-s
    port: 9998
    targetPort: staple-port
    protocol: TCP