kind: Service
apiVersion: v1
metadata:
  namespace: staple
  name: staple-service
  labels:
    app: staple
    app.kubernetes.io/name: staple
    app.kubernetes.io/instance: staple
spec:
  selector:
    app: staple
    app.kubernetes.io/name: staple
    app.kubernetes.io/instance: staple
  ports:
  - name: service-port
    port: 9998
    targetPort: staple-port